### ISSUE TITLE
IOS version neede!

### ISSUE THREAD

**Issue by MaeseppTarvo** [Jolanrensen/PermanentProxy-for-WearOS#13]
Title says it all. If somebody knows any other projects, please link 🙂

**Comment by Jolanrensen** [comment]
What do you mean with an iOS version? An Apple watch version or a Wear OS version that you can install using an iPhone?
The latter you cannot do, but you can install it on the Wear OS watch via ADB.

**Comment by MaeseppTarvo** [comment]
@Jolanrensen I am sorry, I totally misunderstood how it works. I tried it out and the following command returns error: 

`adb shell pm grant nl.jolanrensen.permanentproxy android.permission.WRITE_SECURE_SETTINGS`

> Package nl.jolanrensen.permanentproxy has not requested permission android.permission.WRITE_SECURE_SETTINGS

**Comment by Jolanrensen** [comment]
Alright, to start of: What kind of watch do you have and what kind of phone?
Next, have you installed the wear apk from the releases on your watch using ADB on your pc?
Finally, following the instructions of the app (enabling adb over bluetooth on the watch etc) are you able to get permission and input proxy details?

**Comment by MaeseppTarvo** [comment]
@Jolanrensen I do have Fossil gen 5. I firstly did connect to my watch over wifi. Then I sideloaded the apk to my watch. I do have IOS as phone OS. The problem is  I can not execute the command I wrote.

How it is possible to connect to my watch using bluetooth? As soon as I switch to adb blluetooth, the  connection gets lost and you can not run any commands on watch.

**Comment by Jolanrensen** [comment]
Ah I see. Have you read the Get started?

> To get started, first enable the Developer Options of your watch, which can be achieved by going to Settings -> System -> About and tap the Build number until you are a "developer". Next, go to Settings -> Developer options and enable "ADB debugging" and "Debug over Bluetooth". Finally start up Permanent Proxy, request permission and press "Allow" or "Always allow this Computer" if prompted. After requesting permission, ADB can be turned off again to save battery, unless you want to turn off the proxy completely.
> 
> Now you can get started! Simply enter a proxy address and port, enable it (and on boot if you like) and you're done!

As you can see, you don't need to enter other commands as the app does it itself. ONLY if this doesn't work (fossil gen 5 should do it fine), you can connect back to a pc over wifi or however you like and then you can issue the pm grant command.

**Comment by MaeseppTarvo** [comment]
@Jolanrensen Sorry, I look dumb but I do not understand the part how to request the permission. App itself has no button. Then I thought that I can do it through the adb. Now u say I do not need to connect with wifi but bluetooth. That is what I also tried. But like this I can not enter any commands from pc.

**Comment by Jolanrensen** [comment]
You mean this button? https://photos.app.goo.gl/2y9wZJYNJ7dAXJnK9

**Comment by MaeseppTarvo** [comment]
@Jolanrensen Yep, that button. I do not have it 😄

**Comment by Jolanrensen** [comment]
Then what DO you have?

**Comment by MaeseppTarvo** [comment]
Only the text view with all the instructions, pretty much the readme you have in github. The app does not fit into content properly and the title is also cut from the left, starting with "manent Proxy"

**Comment by Jolanrensen** [comment]
That's the mobile version apk you got installed on your watch... You need the wear-release.apk

**Comment by MaeseppTarvo** [comment]
@Jolanrensen That was the issue. Thank you very much and sorry for wasting your time. I really do not know how I could miss that I downloaded wrong apk..
