### ISSUE TITLE
Side effects when using proxy: geo position

### ISSUE THREAD

**Issue by IvanO-20** [Jolanrensen/PermanentProxy-for-WearOS#20]
Not a bug by permanent proxy, but since this app is using(mostly) for google pay availability, it worth to say about some interesting bug in wearOS+assistance.
When trying to say command, for example "what distance to {city nearby}, google will tell you big amount, from, actually, USA, I suppose. I'm from Ukraine, and google said "5 thousands miles". Although, GPS are writing fine, google maps shows me correctly, weather is also fine, but google assistance and ALL commands think that I'm from USA (my proxy address in Amazon aws).
Just keep in mind about it, mbe it's worth to add to readme

**Comment by Jolanrensen** [comment]
added!
