### ISSUE TITLE
Problem happened on Chinese wear os system

### ISSUE THREAD

**Issue by HauntChoc** [Jolanrensen/PermanentProxy-for-WearOS#21]
I have checked the forum and seems no related problem mentioned.

Device: Ticwatch Pro 3 bought in China
Others: I have set e-sim card

Proxy starts well yet the connection seems broken when I use it to check apps which blocked  in China by GFW.
it usually took 2 or 3 minutes to reboot( before that the network was broken and couldn't check anything )

I Also installed v2ray on my watch
and I found it would be shut down by unknown reason( and when I reboot the watch and link to the v2ray it usually works for about 1 min then later broken )
I have no idea about what caused it and I'm not sure whether it caused by wear os itself or wear os Chinese Version

**Comment by the-25th-Nova** [comment]
with log in v2 it might see clearly
https://github.com/2dust/v2rayNG/issues/941

**Comment by Jolanrensen** [comment]
The proxy is known to not work over cellular data, that might be the issue.

**Comment by the-25th-Nova** [comment]
> 已知代理无法处理蜂窝数据，这可能是问题所在。

It resulted to be the same using WIFI

**Comment by the-25th-Nova** [comment]
> 已知代理无法处理蜂窝数据，这可能是问题所在。

I have solved v2ray problem (https://github.com/2dust/v2rayNG/issues/941)
and it works for cellular data.

it can be a replacement for this issue.

**Comment by the-25th-Nova** [comment]
> 已知代理无法处理蜂窝数据，这可能是问题所在。

you could now close this issue because I dont use that account anymore
