### ISSUE TITLE
Compatibility with wear os keybaord

### ISSUE THREAD

**Issue by eric1357a** [Jolanrensen/PermanentProxy-for-WearOS#6]
Wear OS keyboard not recognize the complete input action as complete instead of search action.

Maybe request input from the phone instead of using watch's keyboard?

**Comment by Jolanrensen** [comment]
Can you elaborate?
The search action button should be visible on the keyboard of the watch right?
I'm not planning on using the phone as input at the moment, because the app should be able to run watch-only.
