### ISSUE TITLE
Proxy cannot enable when the address is including the username and password

### ISSUE THREAD

**Issue by eric1357a** [Jolanrensen/PermanentProxy-for-WearOS#7]
Enabling the proxy button didn't operate normally as the address will not show up on the top of the app.
The username:password@host should be working with the adb command, maybe add the username and password fields separately in the app?

**Comment by Jolanrensen** [comment]
Can you confirm this to be working on android? I tried before to use a proxy with authentication on my phone, but it didn't work. When opening a web browser I still got asked my username and password again and after doing so, no other apps were granted internet access.
